# Generated by Django 4.1.4 on 2023-01-18 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Facets",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=255)),
                ("unit", models.CharField(max_length=255)),
                ("currency", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=255)),
                ("type", models.CharField(max_length=255)),
                ("group", models.CharField(max_length=255)),
                ("frequency", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="TRADINGECONOMICSDATA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("info", models.CharField(max_length=255)),
                ("santase", models.IntegerField()),
                ("hits", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=255)),
                ("doc_count", models.IntegerField(default=0)),
                (
                    "unit_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unit_id",
                        to="mainapp.facets",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Type",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=255)),
                ("doc_count", models.IntegerField(default=0)),
                (
                    "type_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="type_id",
                        to="mainapp.facets",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hits", models.CharField(max_length=255)),
                ("page", models.IntegerField()),
                ("facets", models.CharField(max_length=255)),
                (
                    "info_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="info_id",
                        to="mainapp.tradingeconomicsdata",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Hitsrelationvalue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.IntegerField(default=0)),
                ("relation", models.CharField(max_length=255)),
                (
                    "hits_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hits_id",
                        to="mainapp.info",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Hits",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.IntegerField(default=0)),
                ("relation", models.CharField(max_length=255)),
                ("country", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=255)),
                ("currency", models.CharField(max_length=255)),
                ("iids", models.CharField(max_length=255)),
                ("esID", models.CharField(max_length=255)),
                ("s", models.CharField(max_length=255)),
                ("importance", models.IntegerField(default=0)),
                ("name", models.CharField(max_length=255)),
                ("type", models.CharField(max_length=255)),
                ("group", models.CharField(max_length=255)),
                ("frequency", models.CharField(max_length=255)),
                ("unit", models.CharField(max_length=255)),
                ("pretty_name", models.CharField(max_length=255)),
                ("url", models.CharField(max_length=255)),
                (
                    "hits_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hits_id",
                        to="mainapp.tradingeconomicsdata",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=255)),
                ("doc_count", models.IntegerField(default=0)),
                (
                    "group_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_id",
                        to="mainapp.facets",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Frequency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField()),
                ("key", models.CharField(max_length=255)),
                ("doc_count", models.IntegerField(default=0)),
                (
                    "frequency_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="frequency_id",
                        to="mainapp.facets",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="facets",
            name="facets_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="facets_id",
                to="mainapp.info",
            ),
        ),
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=255)),
                ("doc_count", models.IntegerField(default=0)),
                (
                    "currency_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="currency_id",
                        to="mainapp.facets",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=255)),
                ("doc_count", models.IntegerField(default=0)),
                (
                    "country_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="country_id",
                        to="mainapp.facets",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=255)),
                ("doc_count", models.IntegerField(default=0)),
                (
                    "category_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_id",
                        to="mainapp.facets",
                    ),
                ),
            ],
        ),
    ]
