# Generated by Django 4.1.4 on 2023-01-10 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dataclass", old_name="hits_name", new_name="hits",
        ),
        migrations.AlterField(
            model_name="info",
            name="hits_name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hits_name",
                to="mainapp.dataclass",
            ),
        ),
    ]
